# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_testmodel_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.JobPosting')),
            ],
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='job',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
