# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20180420_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
