# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_applicant_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='curriculum_vitae',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userapplication',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.Applicant'),
        ),
    ]
