# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20180420_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_experience',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
