# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20180420_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationscore',
            name='application',
        ),
        migrations.AddField(
            model_name='userapplication',
            name='match_ratio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='performance',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApplicationScore',
        ),
    ]
