# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 16:39
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_remove_userapplication_match_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='curriculum_vitae',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dan\\Desktop\\2018-ca400-osulld42\\src\\jobanalytics\\backend\\media\\cvs'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file_upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dan\\Desktop\\2018-ca400-osulld42\\src\\jobanalytics\\backend\\media\\cvs'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
