# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 16:45
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20180422_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='applicant',
        ),
        migrations.AddField(
            model_name='userapplication',
            name='curriculum_vitae',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dan\\Desktop\\2018-ca400-osulld42\\src\\jobanalytics\\backend\\media\\cvs'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='education',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.JobPosting'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='last_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='phone_number',
            field=models.CharField(default='0871234567', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapplication',
            name='work_experience',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
