# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 21:47
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20180422_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dan\\Desktop\\2018-ca400-osulld42\\src\\jobanalytics\\backend\\media\\cvs'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])])),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentUpload',
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='curriculum_vitae',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.CVUpload'),
        ),
    ]
