# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 15:59
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20180422_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='cvupload',
            name='education_section',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvupload',
            name='skills_section',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvupload',
            name='work_experience_section',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dan36\\Desktop\\2018-ca400-osulld42\\src\\jobanalytics\\backend\\media\\cvs'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
