# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20180429_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='work_experience',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
