# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_userapplication_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='match_ratio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
