# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_userapplication_match_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='match_ratio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
